html:
	Pweave index.rstw
	rst2html.py index.rst index.html
clean:
	rm -f *.pdf
	rm -f *.out
	rm -f *.aux
	rm -f *.log
	rm -f *.md
	rm -f *.rst
	rm -f *.tex
	rm -f *.html
	rm -rf figures
	rm -rf cache
